#!/bin/bash

# TITLE: edit_sudoers
# AUTHOR: Boardleahs (Derek)
# DATE: Saturday, March 22 2025

# Script to edit the /etc/sudoers file

# Debug
#set -x

##############
## VARIABLES
############A

# Variables for coloring/formatting
bgrn='\033[1;32m'
brd='\033[1;31m'
noc='\033[0m'

# Variable to store username to add to the /etc/sudoers file
username=$1
#user_dir=/etc/passwd

# Edit /etc/sudoers to allow the SUDO_USER to run commands without a password
if [ ! "$SUDO_USER" ]; then
  printf "\nYou are not able to run this script.  Please elevate if you desire to run this script.\n\n"
	exit 126
else
	check_user=$(grep "$username" {/etc/passwd})
	if [ "$check_user" == 0 ]; then
		printf ""$username" ALL=(ALL) NOPASSWD:ALL" >> "$user_dir"
		printf ""\n$bgrn"SUCCESS: "$username" HAS BEEN SUCCESSFULLY ADDED TO THE SUDOERS FILE"$noc"\n\n"
	else
		printf ""$brd"\nFAILED: "$username" DOES NOT EXIST ON THIS SYSTEM"$noc"\n\n"
		exit 1
	fi
fi

# Verify if the /etc/sudoers file is valid
if [ "$(visudo -c)" == 0 ]; then
	printf ""$bgrn"\nSUCCESS: SUDOERS FILE IS VALID"$noc"\n\n"
	exit 0
else
	sed -i '$d' "$user_dir"
	printf ""$brd"\nFAILED: SUDOERS FILE IS NOT VALID.  USER HAS BEEN REMOVED"$noc"\n\n"
	exit 1
fi

# EOF
