#!/bin/bash

# TITLE: shutdown_hosts
# AUTHOR: Boardleash (Derek)
# DATE: Tuesday, March 25 2025

# Check if hosts are online, and, if so, shut them down
# As of 25MAR2025, this script will only work with the 'sysadmin' user

# Debug
#set -x

###############
# VARIABLES
#############

# Log file variable
logfile=/usr/local/bin/script.log

# Variable to store the host to shutdown IF only one host is being targeted
shuthost=$1

# Variable to store the array of hosts
hfile=("avalanche" "freighter" "jellyfish" "pelagia" "sandbar" "stingray" "summit")

###############
# THE SCRIPT
#############

# Verify who the user is that is running this script and stop if it is incorrect user
printf "\n$(date "+%c"): Starting shutdown_hosts script" | tee -a "$logfile"
if [ ! "$SUDO_USER" ]; then
  printf "\n$(date "+%c"): /// UNABLE TO RUN SCRIPT: PLEASE ELEVATE \\\\\\\\\\\\" | tee -a "$logfile"
  exit 126 
fi

# Check if the SPECIFIED host is online, and, if so, shut it down
# If the SPECIFIED host is NOT online, then do nothing
if [ "$shuthost" ]; then
  chkconn=$(ping -c 2 -O "$shuthost")
  if [ "$?" == 0 ]; then
    printf "\n$(date "+%c"): "$shuthost" IS BEING SHUTDOWN NOW" | tee -a "$logfile"
    virsh shutdown "$shuthost"
  else
    printf "\n$(date "+%c"): IS NOT ONLINE" | tee -a "$logfile"
  fi
printf "\n$(date "+%c"): Completed shutdown_hosts script using the SPECIFIED host option" | tee -a "$logfile"
printf "\n\n"
fi

# If no host is specified, then go through the array of hosts and check if they are online
# If they are online, then shut them down.  Otherwise, do nothing
if [ ! "$shuthost" ];then
  for host in "${hfile[@]}"; do
    chkconn=$(ping -c 2 -O "$host")
    if [ "$?" == 0 ]; then
      printf "\n$(date "+%c"): "$host" is ONLINE; SHUTTING DOWN NOW" | tee -a "$logfile"
      virsh shutdown "$host"
    else
      printf "\n$(date "+%c"): "$host" is OFFLINE" | tee -a "$logfile"
    fi
  done
fi
printf "\n$(date "+%c"): Completed shutdown_hosts script using ALL hosts option" | tee -a "$logfile"
printf "\n\n"
sleep 5
printf "\n$(date "+%c"): Initiating check_connections script to verify shutdown"| tee -a "$logfile"

# Verify that the hosts are in fact shutdown.
source /usr/local/bin/check_connections

# EOF
