#!/bin/bash

# TITLE: sshkey_shenanigans
# AUTHOR: Boardleash (Derek)
# DATE: Friday, March 21 2025

# Initiate a user login on mutliple machines after copying over ssh keys

#################
# VARIABLES
###############

# Variable to store the array of hosts
hfile=("avalanche" "freighter" "pelagia" "sandbar" "stingray" "summit")

# Variables for coloring/formatting
bgrn='\033[1;32m'
brd='\033[1;31m'
noc='\033[0m'

# For loop with nested if/else statement to ssh into the hosts and
# provide certain results under certain conditions
for host in "${hfile[@]}"; do
  chkconn=$(ping -c 2 -O "$host")
  if [ "$?" == 0 ]; then
    $(ssh "${USER}"@"$host" 'exit')
  else
    printf "\n"$host" is "$brd"OFFLINE"$noc"\n\n"
  fi
done

# EOF
