#!/bin/bash

# TITLE: startup_hosts
# AUTHOR: Boardleash (Derek)
# DATE: Wednesday, April 2 2025

# Power on VM servers (if they are offline)

# Debug
#set -x

###############
# VARIABLES
#############

# Log file variable
logfile=/usr/local/bin/script.log

# Variable to store a SPECIFIED host
starthost=$1

# Variable to store the array of hosts
hfile=("avalanche" "freighter" "jellyfish" "pelagia" "sandbar" "stingray" "summit")

# This script requires escalated privileges, so let's check if the user is elevated.
printf "\n$(date "+%c"): Starting startup_hosts script" | tee -a "$logfile"
if [ ! $SUDO_USER ]; then
  printf "\n$(date "+%c"): /// UNABLE TO RUN SCRIPT: PLEASE ELEVATE \\\\\\\\\\\\" | tee -a "$logfile"
  exit 126
fi

# For loop with nested if/else statement to ping a SPECIFIED host and notify if online or not
# If the SPECIFIED host is found to be offline, power it on.  Otherwise, do nothing.
if [ "$starthost" ]; then
  chkconn=$(ping -c 2 -q -O "$starthost")
  if [ "$?" != 0 ]; then
    printf "\n$(date "+%c"): "$starthost" OFFLINE: ATTEMPTING TO POWER ON" | tee -a "$logfile"
    virsh start "$starthost"
  else
    printf "\n$(date "+%c"): "$starthost" ONLINE: NOTHING TO DO" | tee -a "$logfile"
  fi
printf "\n$(date "+%c"): Completed startup_hosts script using SPECIFIED host option" | tee -a "$logfile"
fi

# For loop with nested if/else statement to ping the above array and notify if online or not
# If a host is found to be offline, power it on.  Otherwise, do nothing.
if [ ! "$starthost" ]; then
  for host in "${hfile[@]}"; do
    chkconn=$(ping -c 2 -O "$host")
    if [ "$?" != 0 ]; then
      printf "\n$(date "+%c"): "$host" OFFLINE: ATTEMPTING TO POWER ON" | tee -a "$logfile"
      virsh start "$host"
    else
      printf "\n$(date "+%c"): "$host" ONLINE: NOTHING TO DO" | tee -a "$logfile"
    fi
  done
fi
printf "\n$(date "+%c"): Completed startup_hosts script using ALL hosts option" | tee -a "$logfile"
sleep 5
printf "\n$(date "+%c"): Initiating check_connections script to verify startup" | tee -a "$logfile"

# Validate that the hosts are actually online.
source /usr/local/bin/check_connections

# EOF
