#!/bin/bash

# TITLE: update_servers
# AUTHOR: Boardleash (Derek)
# DATE: Tuesday, March 25 2025

# Check if hosts are online, and, if so, determine their distro and update based on distro
# As of 25MAR2025, this script will only work with the 'sysadmin' user

# Debug
#set -x

###############
# VARIABLES
#############

# Log file variable
logfile=/usr/local/bin/script.log

# Variable to store the array of hosts
hfile=("avalanche" "freighter" "pelagia" "sandbar" "stingray" "summit")

# Variable to store the host to update IF only one host is being targeted
uphost=$1

##############
# THE SCRIPT
############

# Verify who the user is that is running this script and stop if it is incorrect user
printf "\n$(date "+%c"): Starting update_servers script" | tee -a "$logfile"
if [ "$USER" != 'sysadmin' ]; then
  printf "\n$(date +"%c"): INVALID USER; EXITING" | tee -a "$logfile"
  exit 126
fi

# Check if SPECIFIED host is online, and, if so, pull the distro information and update, then reboot
if [ "$uphost" ]; then
  chkconn=$(ping -c 2 -O "$uphost")
  if [ "$?" == 0 ] && [ "$(ssh "$USER"@"$uphost" 'grep -i 'rhel' /etc/os-release'; echo $?)" == 0 ]; then
    printf "\n$(date "+%c"): "$uphost" IS BEING UPDATED NOW" | tee -a "$logfile"
    ssh "$USER"@"$uphost" 'sudo dnf -y update && reboot'
  elif [ "$?" == 0 ] && [ "$(ssh "$USER"@"$uphost" 'grep -i 'debain' /etc/os-release'; echo $?)" == 0 ]; then
    printf "\n$(date "+%c"): "$uphost" IS BEING UPDATED NOW" | tee -a "$logfile"
    ssh "$USER"@"$uphost" 'sudo apt -y update && sudo apt -y upgrade && reboot'
  else
    printf "\n$(date "+%c"): "$uphost" IS NOT ONLINE" | tee -a "$logfile"
  fi
fi
    
# If no host is specified, then go through the array of hosts and check if they are online
# If they are online, then check the distro, update accordingly and reboot
if [ ! "$uphost" ]; then
  for host in "${hfile[@]}"; do
    chkconn=$(ping -c 2 -O "$host")
    if [ "$?" == 0 ]; then
      printf "\n$(date "+%c"): Verifying "$host" operating system" | tee -a "$logfile"
      ssh "$USER"@"$host" 'grep -i 'rhel' /etc/os-release'
      if [ "$?" == 0 ]; then
	printf "\n$(date "+%c"): Updating "$host"" | tee -a "$logfile"
        ssh "$USER"@"$host" 'sudo dnf -y update && reboot'
      else
	printf "\n$(date "+%c"): Updating "$host"" | tee -a "$logfile"
        ssh "$USER"@"$host" 'sudo apt update -y && sudo apt upgrade -y && reboot'
      fi	
    else
      printf "\n$(date "+%c"): "$host" is OFFLINE" | tee -a "$logfile"
    fi
  done
fi

# Reboot hosts
printf "\n$(date "+%c"): Rebooting host(s) now" | tee -a "$logfile"
if [ "$uphost" ]; then
  ssh "$USER"@"$uphost" 'reboot'
else
  for host in "${hfile[@]}"; do
    chkconn=$(ping -c 2 -O "$host")
    if [ "$?" == 0 ]; then
      ssh "$USER"@"$host" 'reboot'
    fi
  done
fi
printf "\n$(date "+%c"): Completed update_servers script" | tee -a "$logfile"
sleep 5
printf "\n$(date "+%c"): Initiating check_connections script to verify successful reboot" | tee -a "$logfile"

# Verify that the hosts came back online
source /usr/local/bin/check_connections

# EOF
